-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 10:49:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza321
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza321
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza321` DEFAULT CHARACTER SET utf8 ;
USE `pizza321` ;

-- -----------------------------------------------------
-- Table `pizza321`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza321`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza321`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza321`.`pizzas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`),pizza321composition
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza321`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza321`.`promotion` (
  `id` INT NOT NULL,
  `pizzas_id` INT NOT NULL,
  `descripstion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promotion_pizzas1_idx` (`pizzas_id` ASC) VISIBLE,
  CONSTRAINT `fk_promotion_pizzas1`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `pizza321`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza321`.`composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza321`.`composition` (
  `incredients_id` INT NOT NULL,
  `pizzas_id` INT NOT NULL,
  PRIMARY KEY (`incredients_id`, `pizzas_id`),
  INDEX `fk_incredients_has_pizzas_pizzas1_idx` (`pizzas_id` ASC) VISIBLE,
  INDEX `fk_incredients_has_pizzas_incredients_idx` (`incredients_id` ASC) VISIBLE,
  CONSTRAINT `fk_incredients_has_pizzas_incredients`
    FOREIGN KEY (`incredients_id`)
    REFERENCES `pizza321`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incredients_has_pizzas_pizzas1`
    FOREIGN KEY (`pizzas_id`)
    REFERENCES `pizza321`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
